# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cyaiox
email: gabrieldiaz31@gmail.com
description: This site will be my storage of knowledge, here I'll document all solutions for common problems of development and tricks in my day to day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cyaiox.github.io" # the base hostname & protocol for your site
twitter_username: cyaiox
github_username: cyaiox

# Build settings
markdown: kramdown
